eligible.csv

eligible.csv: add nyabinary email

---

.github/workflows/update-email.yml
eligible.csv

Added email address for user 'cafkafk'.

Update 'cafkafk' entry with email

---

eligible.csv

eligible.csv: mindavi: add email

---

eligible.csv

I am in the list of eligible users, add my email so that I will be able to vote

artemist: Add email address

---

eligible.csv

Add email for normalcea

---

eligible.csv

My email address. Not sure whether it is needed, but here it is.

Add email of myself

---

eligible.csv

Added email address for zebreus in eligible.csv

Add email for zebreus

---

eligible.csv

we migth use `lib.maintainers` to autofill mails next time?

Update eligible.csv add my mail

---

eligible.csv

A granted exception request and getting a race-condition-hit edit unstuck

Manual voter registration actions

---

eligible.csv

Add email for rc-zb

---

eligible.csv

Add email address for amozeo in eligible.csv

Add email for amozeo

---

eligible.csv

Add email for Majiir

---

eligible.csv

Updated email for katexochen in eligible.csv

Add email for katexochen

---

candidates/niklaskorz.md

Updates to motivation, reordering of goals, and also small updates based on recent changes.

Update niklaskorz candidate template

---

eligible.csv

Added email address for CyberShadow in eligible.csv

Update CyberShadow's entry with email

---

eligible.csv

Added email address for user 'ryantm'.

Add email for user 'ryantm' in eligible.csv

---

eligible.csv

Change-Id: I6a6a6964314bc99cc51a344053d259f09a5a05fc

Add e-mail for NotAShelf

---

eligible.csv

Updated email address for marcusramberg.

Add email for marcusramberg in eligible.csv

---

candidates/nyabinary.md

(Accepting a correction after the deadline has been permitted by an EC decision)

Candidate statement: nyanbinary: correct a misunderstanding

---

eligible.csv

Registering to vote in the 2025 SC election.

Add email for roberth

---

eligible.csv

Add my email to the eligible list

Add email for returntoreality
